### ISSUE TITLE
Provide a nicer error message when users return non-recognizable values from functions with AOTAutograd.

### ISSUE THREAD

**Issue by hyunwoongko** [pytorch/functorch#475]
Test case 1:
Is it correct? I used this line https://github.com/pytorch/functorch/blob/main/functorch/_src/compilers.py#L11

```python
from transformers import BertTokenizer, BertForMaskedLM
from functorch.compile.compilers import memory_efficient_fusion

model = BertForMaskedLM.from_pretrained("bert-base-cased").cuda()
tokenizer = BertTokenizer.from_pretrained("bert-base-cased")

model = memory_efficient_fusion(model)
model(**tokenizer("hello I am Kevin.", return_tensors="pt").to("cuda"))
```

```
def forward(self, primals_1, primals_2, primals_3, primals_4, primals_5, primals_6, primals_7, primals_8, primals_9, primals_10, primals_11, primals_12, primals_13, primals_14, primals_15, primals_16, primals_17, primals_18, primals_19, primals_20, primals_21, primals_22, primals_23, primals_24, primals_25, primals_26, primals_27, primals_28, primals_29, primals_30, primals_31, primals_32, primals_33, primals_34, primals_35, primals_36, primals_37, primals_38, primals_39, primals_40, primals_41, primals_42, primals_43, primals_44, primals_45, primals_46, primals_47, primals_48, primals_49, primals_50, primals_51, primals_52, primals_53, primals_54, primals_55, primals_56, primals_57, primals_58, primals_59, primals_60, primals_61, primals_62, primals_63, primals_64, primals_65, primals_66, primals_67, primals_68, primals_69, primals_70, primals_71, primals_72, primals_73, primals_74, primals_75, primals_76, primals_77, primals_78, primals_79, primals_80, primals_81, primals_82, primals_83, primals_84, primals_85, primals_86, primals_87, primals_88, primals_89, primals_90, primals_91, primals_92, primals_93, primals_94, primals_95, primals_96, primals_97, primals_98, primals_99, primals_100, primals_101, primals_102, primals_103, primals_104, primals_105, primals_106, primals_107, primals_108, primals_109, primals_110, primals_111, primals_112, primals_113, primals_114, primals_115, primals_116, primals_117, primals_118, primals_119, primals_120, primals_121, primals_122, primals_123, primals_124, primals_125, primals_126, primals_127, primals_128, primals_129, primals_130, primals_131, primals_132, primals_133, primals_134, primals_135, primals_136, primals_137, primals_138, primals_139, primals_140, primals_141, primals_142, primals_143, primals_144, primals_145, primals_146, primals_147, primals_148, primals_149, primals_150, primals_151, primals_152, primals_153, primals_154, primals_155, primals_156, primals_157, primals_158, primals_159, primals_160, primals_161, primals_162, primals_163, primals_164, primals_165, primals_166, primals_167, primals_168, primals_169, primals_170, primals_171, primals_172, primals_173, primals_174, primals_175, primals_176, primals_177, primals_178, primals_179, primals_180, primals_181, primals_182, primals_183, primals_184, primals_185, primals_186, primals_187, primals_188, primals_189, primals_190, primals_191, primals_192, primals_193, primals_194, primals_195, primals_196, primals_197, primals_198, primals_199, primals_200, primals_201, primals_202, primals_203, primals_204, primals_205, primals_206, primals_207, primals_208, primals_209):
    _tensor_constant13 = self._tensor_constant13
    return [_tensor_constant13]

def forward(self, tangents_1):
    return [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
```

**Comment by hyunwoongko** [comment]
Test case 2:
```python
import torch
from transformers import BertLayer, BertConfig
from functorch ...

emb = BertLayer(BertConfig.from_pretrained("bert-base-cased"))

config = {
    "fw_compiler": ts_compile,
    "bw_compiler": ts_compile,
    "hasher_type": "StaticShapheHasher",
    "decompositions": default_decompositions,
}

traced = aot_function(emb.forward, **config)
inputs = {"hidden_states": torch.randn(1, 1, 768), "attention_mask": torch.zeros(1, 1, 1, 1)}
output = traced(**inputs)
```

```
Traceback of TorchScript (most recent call last):
  File "<eval_with_key>.3", line 7, in forward
    view = torch.ops.aten.view(primals_2, [1, 768])
    _tensor_constant0 = self._tensor_constant0
    mm = torch.ops.aten.mm(view, _tensor_constant0);  view = _tensor_constant0 = None
         ~~~~~~~~~~~~~~~~~ <--- HERE
    _unsafe_view = torch.ops.aten._unsafe_view(mm, [1, 1, 768]);  mm = None
    _param_constant0 = self._param_constant0
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_mm)
```

**Comment by Chillee** [comment]
Fixed by https://github.com/pytorch/functorch/commits/main

**Comment by hudoudou29** [comment]
I try this case, however, the error is still happening. I just use the code shown above:

from transformers import BertTokenizer, BertForMaskedLM
from functorch.compile import memory_efficient_fusion

model = BertForMaskedLM.from_pretrained("bert-base-cased")
tokenizer = BertTokenizer.from_pretrained("bert-base-cased")
import torch.utils._pytree as pytree
import transformers
pytree._register_pytree_node(transformers.modeling_outputs.MaskedLMOutput, lambda x: ([x.loss, x.logits], None), lambda values, _: transformers.modeling_outputs.MaskedLMOutput(loss=values[0], logits=values[1]))
model = memory_efficient_fusion(model)
model(**tokenizer("hello I am Kevin.", return_tensors="pt"))
